apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  selector:
    matchLabels:
      app: data-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
