apiVersion: apps/v1
kind: Deployment
metadata:
  name: drupal
  labels:
    app: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  template:
    metadata:
      labels:
        app: drupal
    spec:
      containers:
      - name: drupal
        image: drupal:8.6
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /var/www/html/modules
            name: drupal-vol
            subPath: modules
          - mountPath: /var/www/html/profiles
            name: drupal-vol
            subPath: profiles
          - mountPath: /var/www/html/sites
            name: drupal-vol
            subPath: sites
          - mountPath: /var/www/html/themes
            name: drupal-vol
            subPath: themes
      initContainers:
      - name: init-sites-volume
        image: drupal:8.6
        volumeMounts:
          - mountPath: /data
            name: drupal-vol
        command: [ "/bin/bash", "-c" ]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
      volumes:
        - name: drupal-vol
          persistentVolumeClaim:
            claimName: drupal-pvc
